<?php 

    define("BASE_URL", "http://127.0.0.1/shop/");
    define("HOME_PAGE_URL", BASE_URL);
    define("CUSTOMER_CONTROL_PANEL_URL", BASE_URL."panel/");
    define("LOGIN_PAGE_URL", BASE_URL."panel/login.php");
    define("SIGNUP_PAGE_URL", BASE_URL."panel/signup.php");
    define("LOGOUT_PAGE_URL", BASE_URL."panel/logout.php");
    define("BASKET_PAGE_URL", BASE_URL."shop-basket.php");
    define("NOT_FOUND_PAGE_URL", BASE_URL."not-found.php");
    define("CONTROL_PANEL_URL", BASE_URL."admin/");
    define("CONTROL_PANEL_LOGIN_URL", BASE_URL."admin/login.php");
    define("CONTROL_PANEL_LOGOUT_URL", BASE_URL."admin/logout.php");
    define("FIRST_USER_SIGNUP_URL", BASE_URL."admin/first-user-signup.php");
    define("ADD_NEW_PRODUCT_URL", BASE_URL."admin/add-product.php");
    define("EDIT_PRODUCT_URL", BASE_URL."admin/edit-product.php");
    define("PRODUCTS_IMAGES_URL", BASE_URL."products/");
    define("PRODUCTS_IMAGES_PATH", $_SERVER['DOCUMENT_ROOT']."/shop/products/");
    define("ERROR_PAGE_URL",  BASE_URL."admin/error-page.php");
    define("ADD_NEW_USER_URL", BASE_URL."admin/add-user.php");
    define("EDIT_USER_URL", BASE_URL."admin/edit-user.php");
    define("ADD_NEW_CUSTOMER_URL", BASE_URL."admin/add-customer.php");
    define("EDIT_CUSTOMER_URL", BASE_URL."admin/edit-customer.php");
    define("ORDER_DETAILS_URL", BASE_URL."admin/order-details.php");
    define("ORDER_RECEIPT_URL", BASE_URL."panel/receipt.php");
    define("MAIN_LOGO", BASE_URL."theme/imgs/logo.png");
    define("BASKET_ICON", BASE_URL."theme/imgs/basket.png");
    define("DEFAULT_IMAGE", BASE_URL."admin/imgs/default-image.png");
    define("ALT_255", " ");    
    define("SUCCESS", "موفق");
    define("FAILED", "ناموفق");
    define("HOME", "صفحه اصلی");
    define("FULL_NAME", "نام");
    define("USERNAME", "نام کاربری");
    define("PASSWORD", "کلمه عبور");
    define("LOGIN", "ورود");
    define("CREATE_ACCOUNT", "ایجاد حساب");
    define("BASKET", "سبد خرید");
    define("PRODUCTS_LIST", "لیست محصولات");
    define("SEARCH", "جستجو");
    define("ADD_TO_BASKET", "افزودن به سبد");
    define("COPYRIGHT", "طراحی و توسعه : ابوالفضل شریفی | تقدیم به استاد بهزادی عزیز ");
    define("NOT_FOUND_MESSAGE", "صفحه مورد نظر پیدا نشد!");
    define("BACK_TO_HOME", "بازگشت به صفحه اصلی");
    define("OR_WORD", "یا");
    define("SEARCH_RESULT", "نتیجه جستجو");
    define("EDIT", "ویرایش");
    define("DELETE", "حذف");
    define("CANCEL", "لغو");
    define("SHOW", "نمایش");
    define("INDEX", "ردیف");
    define("SUBMIT", "ثبت");
    define("PHONE", "تلفن");
    define("ADDRESS", "آدرس");
    define("Date", "تاریخ ورود");
    define("ID", "شناسه");
    define("IMAGE", "تصویر");
    define("CAPTION", "عنوان");
    define("UNIT_PRICE", "قیمت واحد");
    define("TOTAL_PRICE", "قیمت کل");
    define("QUANTITY", "تعداد");
    define("AMOUNT", "موجودی");
    define("TOTAL_QUANTITY", "تعداد محصولات");
    define("PAY", "پرداخت");
    define("PAYMENT_STATUS", "وضعیت پرداخت");
    define("ORDER_PRICE", "قابل پرداخت");
    define("DATE_TIME", "تاریخ/زمان");
    define("CUSTOMER", "مشتری");
    define("SHOPPING_CART_CAPTION", "سبد خرید");
    define("LOGIN_TO_ACCOUNT", "ورود به حساب کاربری");
    define("CUSTOMER_PANEL", "پنل مشتری");
    define("ACCOUNT_INFO", "اطلاعات حساب");
    define("CHANGE_PASSWORD", "تغییر کلمه عبور");
    define("ORDERS", "سفارشات");
    define("Comm", "کامنت ها");
    define("RECEIPTS", "رسیدهای شما");
    define("LOGOUT", "خروج از حساب کاربری");
    define("ACCOUNT", "حساب کاربری");
    define("SHOW_SITE", "نمایش سایت");
    define("CURRENT_PASSWORD", "کلمه عبور فعلی");
    define("NEW_PASSWORD", "کلمه عبور جدید");
    define("NEW_PASSWORD_CONFIRM", "تایید کلمه عبور جدید");
    define("ORDER_RECEIPT_CAPTION", "رسید خرید");
    define("PAID_PRICE", "مبلغ پرداخت شده");
    define("ORDER_PAYMENT_STATUS", "وضعیت پرداخت");
    define("PRODUCTS_COUNT", "تعداد محصولات");
    define("BUY_DETAILS", "جزئیات خرید");
    define("PRIMARY_SEPARATOR", " | ");
    define("SECONDARY_SEPARATOR", " < ");
    define("SITE_TITLE", "فروشگاه آنلاین");
    define("CUSTOMER_LOGIN_TITLE", "ورود به حساب کاربری".PRIMARY_SEPARATOR.SITE_TITLE);
    define("CUSTOMER_SIGNUP_TITLE", "ایجاد حساب کاربری".PRIMARY_SEPARATOR.SITE_TITLE);
    define("BASKET_TITLE", "سبد خرید".PRIMARY_SEPARATOR.SITE_TITLE);
    define("SEARCH_TITLE", "جستجو".PRIMARY_SEPARATOR.SITE_TITLE);
    define("NOT_FOUND_TITLE", "موضوع پیدا نشد".PRIMARY_SEPARATOR.SITE_TITLE);
    define("PRODUCT_DETAILS_TITLE", "جزئیات محصول".PRIMARY_SEPARATOR.SITE_TITLE);
    define("CONTROL_PANEL_TITLE", "پنل مدیریت".PRIMARY_SEPARATOR.SITE_TITLE);
    define("MANAGE_PRODUCTS_TITLE", "مدیریت محصولات".SECONDARY_SEPARATOR.CONTROL_PANEL_TITLE);
    define("ADD_PRODUCT_TITLE", "ثبت محصول جدید".SECONDARY_SEPARATOR.CONTROL_PANEL_TITLE);
    define("EDIT_PRODUCT_TITLE", "ویرایش محصول".SECONDARY_SEPARATOR.CONTROL_PANEL_TITLE);
    define("MANAGE_USERS_TITLE", "مدیریت کاربران".SECONDARY_SEPARATOR.CONTROL_PANEL_TITLE);
    define("ADD_USER_TITLE", "ثبت کاربر جدید".SECONDARY_SEPARATOR.CONTROL_PANEL_TITLE);
    define("EDIT_USER_TITLE", "ویرایش کاربر".SECONDARY_SEPARATOR.CONTROL_PANEL_TITLE);
    define("MANAGE_CUSTOMERS_TITLE", "مدیریت مشتریان".SECONDARY_SEPARATOR.CONTROL_PANEL_TITLE);
    define("ADD_CUSTOMER_TITLE", "ثبت مشتری جدید".SECONDARY_SEPARATOR.CONTROL_PANEL_TITLE);
    define("EDIT_CUSTOMER_TITLE", "ویرایش مشتری".SECONDARY_SEPARATOR.CONTROL_PANEL_TITLE);
    define("ORDERS_LIST_TITLE", "لیست سفارشات".SECONDARY_SEPARATOR.CONTROL_PANEL_TITLE);
    define("ORDER_DETAILS_TITLE", "جزئیات سفارش".SECONDARY_SEPARATOR.CONTROL_PANEL_TITLE);
    define("FIRST_USER_SIGNUP_CAPTION", "ثبت کاربر اصلی");
    define("ADMIN_LOGIN_CAPTION", "ورود به پنل مدیریت");
    define("LOGIN_ERROR_MESSAGE", "نام کاربری یا کلمه عبور اشتباه است!");
    define("SIGNUP_EMPTY_FIELD_ERROR_MESSAGE", "شما باید تمام فیلد ها را پر کنید!");
    define("USERNAME_EXISTENCE_ERROR_MESSAGE", "این نام کاربری قبلا ثبت شده است!");
    define("ADD_NEW_PRODUCT", "محصول جدید");
    define("EDIT_PRODUCT", "ویرایش محصول");
    define("SUCCESSFUL_DELETE_MESSAGE", "محصول مورد نظر با موفقیت حذف شد.");
    define("FAILURE_DELETE_MESSAGE", "در انجام عملیات خطایی رخ داده است!");
    define("USERS_LIST", "لیست کاربران");
    define("ADD_NEW_USER", "کاربر جدید");
    define("EDIT_USER", "ویرایش کاربر");
    define("CUSTOMERS_LIST", "لیست مشتریان");
    define("ADD_NEW_CUSTOMER", "مشتری جدید");
    define("EDIT_CUSTOMER", "ویرایش مشتری");
    define("MANAGE_PRODUCTS", "مدیریت محصولات");
    define("MANAGE_CUSTOMERS", "مدیریت مشتریان");
    define("MANAGE_USERS", "مدیریت کاربران");
    define("PRODUCT_DESCRIPTION", "توضیحات محصول");
    define("SUCCESS_DELETE_MESSAGE", "عملیات حذف با موفقیت انجام شد.");
    define("FAILED_DELETE_MESSAGE", "عملیات حذف ناموفق بود!");
    define("ADD_CUSTOMER_EMPTY_FIELD_MESSAGE", "نام، نام کاربری و کلمه عبور نمی تواند خالی باشد!");
    define("ADD_CUSTOMER_SUCCESS_MESSAGE", "مشتری جدید با موفقیت ثبت شد.");
    define("ADD_CUSTOMER_FAILED_MESSAGE", "خطایی در ثبت مشتری رخ داده است!");
    define("EDIT_CUSTOMER_SUCCESS_MESSAGE", "اطلاعات مشتری با موفقیت ویرایش شد.");
    define("EDIT_CUSTOMER_FAILED_MESSAGE", "خطایی در ویرایش اطلاعات رخ داده است!");
    define("ADD_PRODUCT_SUCCESS_MESSAGE", "محصول جدید با موفقیت ثبت شد.");
    define("ADD_PRODUCT_FAILED_MESSAGE", "خطایی در ثبت محصول رخ داده است!");
    define("EDIT_PRODUCT_SUCCESS_MESSAGE", "اطلاعات محصول با موفقیت ویرایش شد.");
    define("EDIT_PRODUCT_FAILED_MESSAGE", "خطایی در ویرایش اطلاعات رخ داده است!");
    define("ADD_USER_SUCCESS_MESSAGE", "کاربر جدید با موفقیت ثبت شد.");
    define("ADD_USER_FAILED_MESSAGE", "خطایی در ثبت کاربر رخ داده است!");
    define("EDIT_USER_SUCCESS_MESSAGE", "اطلاعات کاربر با موفقیت ویرایش شد.");
    define("EDIT_USER_FAILED_MESSAGE", "خطایی در ویرایش اطلاعات رخ داده است!");